#' Simulated data set from Serrano-Pérez & Sucar (2021)
#'
#' This data set with hierarchically structured outcome is one of the artificial data sets generated by Serrano-Pérez & Sucar (2021).
#'
#' The variables are as follows:
#' \itemize{
#'   \item \code{x1}, \code{x2}, ..., \code{x13}. metric. Metric covariates
#'   \item \code{ydepvar}. factor. Hierarchical outcome variable
#' }
#' \verb{ }\cr
#' We processed the original data set by restructuring the outcome in the way required by
#' \code{\link{topdown}} and \code{\link{predict.topdown}}.
#'
#' @format A data frame with 560 observations, 13 covariates and one hierarchical outcome variable
#' @source The data set (as many other artificial data sets with hierarchically structured outcome)
#' is available from a GitHub repository (file name: \code{HA_02_FD_b_train.arff}, second commit, date of commit: 13 Jul 2019). Link: \url{https://github.com/jona2510/ADforHC/}
#'
#' @examples
#' # Load data:
#' data(datasim)
#'
#' # Dimension of data:
#' dim(datasim)
#'
#' # First rows of data:
#' head(datasim)
#'
#' @references
#' \itemize{
#'   \item Serrano-Pérez, J., Sucar, L. (2021). Artificial datasets for hierarchical classification. Expert Systems With Applications, 182, 115218.
#'   }
#'
#' @name datasim
NULL
